version: "3.8"

services:
  app:
    container_name: sait-back-app
    image: sait-back-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file: 
      - .env
    ports:
      - 4000:4000
