version: "3.8"

services:
  sait-back:
    container_name: sait-back
    image: sait-back_local:${DOCKER_TAG:-latest}
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000