const init = async () => {

  return `

  DROP TABLE users cascade;
  DROP TABLE technicians cascade;
  DROP TABLE components cascade;
  DROP TABLE devices cascade;
  DROP TABLE errors cascade;
  DROP TABLE types cascade;
  DROP TABLE incidences cascade;
  DROP TABLE user_incidences cascade;
  DROP TABLE device_components cascade;
  DROP TABLE device_incidences cascade;
  DROP TABLE incidence_errors cascade;
  DROP TABLE technician_errors cascade;

  CREATE TABLE "components" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "picture" varchar(400),
    "picture_id" varchar(400),
    "description" varchar(400) NOT NULL,
    CONSTRAINT "_copy_8" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "device_components" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "component_id" int4 NOT NULL,
    "device_id" int4 NOT NULL,
    CONSTRAINT "_copy_7" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "device_incidences" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "incidence_id" int4,
    "device_id" int4,
    CONSTRAINT "_copy_5" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "devices" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "user_id" int4 NOT NULL,
    "serial" varchar(255) NOT NULL,
    CONSTRAINT "_copy_4" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "errors" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "description" varchar(255) NOT NULL,
    "date" date NOT NULL,
    "priority" int8,
    CONSTRAINT "_copy_6" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "incidence_errors" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "error_id" int4 NOT NULL,
    "incidence_id" int4 NOT NULL,
    CONSTRAINT "_copy_3" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "incidences" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "description" varchar(255) NOT NULL,
    "type_id" int4 NOT NULL,
    CONSTRAINT "_copy_2" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "technician_errors" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "error_id" int4 NOT NULL,
    "technician_id" int4 NOT NULL,
    CONSTRAINT "_copy_10" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "technicians" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "user_id" int4 NOT NULL,
    CONSTRAINT "_copy_1" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "types" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    PRIMARY KEY ("id")
  );
  
  CREATE TABLE "user_incidences" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "user_id" int4 NOT NULL,
    "incidence_id" int4 NOT NULL,
    CONSTRAINT "_copy_11" PRIMARY KEY ("id")
  );
  
  CREATE TABLE "users" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY,
    "first_name" varchar(255) NOT NULL,
    "last_name" varchar(255) NOT NULL,
    "dni" varchar(255) NOT NULL,
    "email" varchar(255) NOT NULL,
    "birth_date" date NOT NULL,
    "role" int8 NOT NULL,
    "password" varchar(500) NOT NULL,
    "profile_picture" varchar(400),
    "profile_picture_id" varchar(400),
    "sex" varchar(1) NOT NULL,
    CONSTRAINT "_copy_9" PRIMARY KEY ("id")
  );
  
  ALTER TABLE "device_components" ADD CONSTRAINT "device_components_device_id" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "device_components" ADD CONSTRAINT "device_components_component_id" FOREIGN KEY ("component_id") REFERENCES "components" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "device_incidences" ADD CONSTRAINT "device_incidences_device_id" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "device_incidences" ADD CONSTRAINT "device_incidences_error_id" FOREIGN KEY ("incidence_id") REFERENCES "incidences" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "devices" ADD CONSTRAINT "user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "incidence_errors" ADD CONSTRAINT "incidence_errors_error_id" FOREIGN KEY ("error_id") REFERENCES "errors" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "incidence_errors" ADD CONSTRAINT "incidence_errors_incidence_id" FOREIGN KEY ("incidence_id") REFERENCES "incidences" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "incidences" ADD CONSTRAINT "incidence_type_id" FOREIGN KEY ("type_id") REFERENCES "types" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "technician_errors" ADD CONSTRAINT "technician_errors_error_id" FOREIGN KEY ("error_id") REFERENCES "errors" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "technician_errors" ADD CONSTRAINT "technician_errors_technician_id" FOREIGN KEY ("technician_id") REFERENCES "technicians" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "technicians" ADD CONSTRAINT "technician_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "user_incidences" ADD CONSTRAINT "user_incidences_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE "user_incidences" ADD CONSTRAINT "user_incidences_incidence_id" FOREIGN KEY ("incidence_id") REFERENCES "incidences" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;  
  `
}

module.exports = init