const bcrypt = require('bcryptjs');

const init = async () => {
  
  let salt = await bcrypt.genSalt(15);
  
  let hashedAdminPass = await bcrypt.hash('admin', salt);
  let hashedUserPass = await bcrypt.hash('user', salt);

  return `
  -- -----------------------------------------------------
  -- Schema mydb
  -- -----------------------------------------------------
  
  -- -----------------------------------------------------
  -- Table users
  -- -----------------------------------------------------
  
  DROP TABLE IF EXISTS users;
  
  CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password VARCHAR(1000) NOT NULL,
    sex VARCHAR(45) NOT NULL,
    dni VARCHAR(45) NOT NULL,
    profile_picture VARCHAR(200),
    profile_picture_id VARCHAR(200),
    role INT NOT NULL,
    birth_date DATE NOT NULL
  );
  
  INSERT INTO users (first_name, last_name, email, password, sex, dni, role, birth_date) VALUES ('admin', 'admin', 'admin@admin.com', '${hashedAdminPass}', 'F', '11111111111', '60', '1995-12-17T03:24:00');
  
  INSERT INTO users (first_name, last_name, email, password, sex, dni, role, birth_date) VALUES ('user', 'user', 'user@user.com', '${hashedUserPass}', 'F', '11111111111', '50', '1995-12-17T03:24:00');
  `
}

module.exports = init