const bcrypt = require('bcryptjs');

const init = async () => {
  
  let salt = await bcrypt.genSalt(15);
  
  let hashedAdminPass = await bcrypt.hash('admin', salt);
  let hashedUserPass = await bcrypt.hash('user', salt);

  return `
  -- -----------------------------------------------------
  -- Schema mydb
  -- -----------------------------------------------------
  
  -- -----------------------------------------------------
  -- Table profiles
  -- -----------------------------------------------------
  
  DROP TABLE IF EXISTS profiles;
  
  CREATE TABLE IF NOT EXISTS profiles (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password VARCHAR(1000) NOT NULL,
    sex VARCHAR(45) NOT NULL,
    dni VARCHAR(45) NOT NULL,
    role INT NOT NULL,
    birth_date DATE NOT NULL
  );
  
  INSERT INTO profiles (first_name, last_name, email, password, sex, dni, role, birth_date) VALUES ('admin', 'admin', 'admin@admin.com', '${hashedAdminPass}', 'f', '11111111111', '60', '10/10/2020');
  
  INSERT INTO profiles (first_name, last_name, email, password, sex, dni, role, birth_date) VALUES ('user', 'user', 'user@user.com', '${hashedUserPass}', 'f', '11111111111', '50', '10/10/2020');
  `
}

module.exports = init